datasets:
  feature_face_caption:
    data_type: images
    
    build_info:
      image_path: /export/home/scratch/qze/emotion-llama/MER2023+MER2024

      ann_path: /export/home/scratch/qze/emotion-llama/MER2023+MER2024/relative_train_NCEV.txt
      # ann_path: /export/home/scratch/qze/emotion-llama/MER2023+MER2024/MERR_coarse_grained.txt
      # ann_path: /export/home/scratch/qze/emotion-llama/MER2023+MER2024/MERR_fine_grained.txt
