model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/local/user/qze/Code/Emotion-LLaMA/checkpoints/Llama-2-7b-chat-hf"
  ckpt: "/export/home/scratch/qze/checkpoint/stage2/checkpoint_best.pth"
  lora_r: 64
  lora_alpha: 16

datasets:    
  feature_face_caption:  #
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

evaluation_datasets:
  feature_face_caption:
    eval_file_path: /export/home/scratch/qze/relative_test3_NCEV.txt

    img_path: /export/home/scratch/qze/emotion-llama/MER2023+MER2024

    max_new_tokens: 500
    batch_size: 1

  mer2024_caption:
    eval_file_path: /export/home/scratch/qze/MER2024-noise_NCE.txt
    img_path: /export/home/scratch/qze/emotion-llama/MER2023+MER2024
    max_new_tokens: 500
    batch_size: 1  

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /export/home/scratch/qze/results
